### ISSUE TITLE
poor performance when reading large csv files

### ISSUE THREAD

**Issue by thumbert** [close2/csv#1]
Hi, 

Thanks for providing this package.  I've tried to read in a large csv file 165,000 rows, 20 colums about 30 MB of data.  It took more than 1 min to convert the file into a List<List<String>>.  

  Stopwatch stopwatch = new Stopwatch()..start();
  var str = new File("testfile.csv").readAsStringSync();  // the read part is very fast
  List<List<String>> aux = const CsvToListConverter(eol: "\n").convert(str);
  print("Took ${stopwatch.elapsed} to read csv file");

This is with Dart 1.8.5.  

For comparison, R reads the data into a data.frame in less than 5 seconds.  

Is there anything that can be done to speed up the Dart implementation?

Thanks, 
Tony

**Comment by close2** [comment]
Hi Tony,

I will take a look into this.

Did you consider using the converter as stream/transformer?

**Comment by close2** [comment]
Just a note: Profiler says that I spend ~80-90% in try-catch of int/double.parse.

I don't have your CSV file, but chances are high, that my next version is much faster.
