### ISSUE TITLE
Dart 1.17.1 pub get not finding csv: 3.0.1

### ISSUE THREAD

**Issue by Zectbumo** [close2/csv#11]
I ran a fresh pub get using Dart 1.17.1 and it can't find csv 3.0.1
```
$ dart --version
Dart VM version: 1.17.1 (Fri Jun 10 04:46:03 2016) on "macos_x64"

$ cat pubspec.yaml 
name: "enchilada"
dependencies:
  browser: "^0.10.0+2"
  csv: ^3.0.1

$ pub get
Resolving dependencies... 
Package csv has no versions that match >=3.0.1 <4.0.0 derived from:
- enchilada depends on version ^3.0.1
```

**Comment by close2** [comment]
Thanks for reporting!

pub should now find version 3.1.1 when using ^3.0.1.

I don't really understand why pub didn't find 3.0.1.

In any case I had not executed `pub publish` for my recent versions, which not only publishes version 3.1.1 but also fixes this bug.
