### ISSUE TITLE
Encoding strings

### ISSUE THREAD

**Issue by jtrunick** [close2/csv#12]
First of all, thanks for the library, very helpful.

I'm writing string values, and I even have them typed as such, but the library is deciding when to quote them, this is causing a string value of "1973" to be attempted to read as a number which fails as I'm trying to read it as a string again. So, right not I can't read the same file the library wrote.

Let me know if I'm using it incorrectly, my current workaround is to tell it to not decode any numbers, but that doesn't let me have numeric columns.

I'd appreciate it if I could tell the encoder to always encode strings with quotes, and leave numeric types w/o quotes. Barring that, the next best thing would be to specify on encode/decode how to encode each column.

**Comment by close2** [comment]
I think the current approach concerning type conversions is broken.

Version 1.x won't change this behavior.

For now it is probably better to not parse numbers (shouldParseNumbers: false) and manually map rows.
You probably know what's in
