### ISSUE TITLE
csv 3.2.0 doesn't work with dart 1.24.3

### ISSUE THREAD

**Issue by sestegra** [close2/csv#21]
```
'package:csv/csv_to_list_converter.dart': malformed type: line 8 pos 34: cannot resolve class 'StreamTransformerBase' from 'CsvToListConverter'
class CsvToListConverter extends StreamTransformerBase<String, List>
```

**Comment by evanweible-wf** [comment]
It was this change that introduced this issue:

https://github.com/close2/csv/commit/235d89854b86ef9f2e2e864d138ce96ab38b4a0d

The `StreamTransformerBase` (from `dart:async`) is only available in Dart 2+. This change should have been released with an accompanying change to the pubspec.yaml to limit the SDK to Dart 2.

**Comment by evanweible-wf** [comment]
@close2 could this be fixed in a patch?
