### ISSUE TITLE
"A value of type 'dynamic' can't be assigned to a variable of type 'String'."

### ISSUE THREAD

**Issue by close2** [close2/csv#26]
I also get :
"A value of type 'dynamic' can't be assigned to a variable of type 'String'."
In : lib/csv_settings_autodetection.dart

_Originally posted by @926 in https://github.com/close2/csv/issues/6#issuecomment-471579238_

**Comment by close2** [comment]
@926 I can not reproduce this.  Could you please provide a minimal example, or the line number.

**Comment by lil5** [comment]
```dart
Future<List<List<String>>> fromCSVFile() async {
  String file = "assets/data/story.csv";
  final csvString = await rootBundle.loadString(file);

  /// csv type is List<List<dynamic>>
  final csv = _csvConverter.convert(
    csvString,
    fieldDelimiter: " ",
    textDelimiter: "\"",
    textEndDelimiter: "\"",
    eol: "\n",
    shouldParseNumbers: false,
  );

  /// the wish is to return a string list list
  /// but results in this error https://github.com/flutter/flutter/issues/18979
  return csv as List<List<String>>;
}
```

**Comment by lil5** [comment]
I have made a working PR fixing the issue.

@close2 if you are interested please give me a heads up and I'll make some time to adjust documentation.

**Comment by close2** [comment]
@lil5 I might have published 5.0.1 too soon.  Is you PR not backwards compatible?

**Comment by lil5** [comment]
I'll have a look tomorrow

**Comment by lil5** [comment]
> Is you PR not backwards compatible?

As you can now see in my new PR #47, **Yes** PR #46 (that is merged) is already backwards compatible.

In dart generics if not explicitly stated, are type `generic`.

**Comment by flutter-painter** [comment]
Well done and thanks
