### ISSUE TITLE
Csv content cannot display Traditional Chinese if open in Excel

### ISSUE THREAD

**Issue by tkchung23** [close2/csv#41]
hi , I am using csv 5.0.0 plugin, and try to export the csv file which contains Traditional Chinese to Flutter Web. After export the file , using notepad open the file is OK, however open in Excel the content will become  (???????? ) . Can you help with this? Thanks

Sample Code as below:

`
import 'package:csv/csv.dart';

String fileName = "testFile.csv";
List<List<dynamic>> wholeFile = new List<List<dynamic>>();
wholeFile.add(["姓", "名", "性別"]);
wholeFile.add(["陳", "大文", "男"]);
String csvString = ListToCsvConverter().convert(wholeFile);
 new html.AnchorElement(href: "data:text/plain;charset=utf-8,$csvString")
      ..setAttribute("download", "$fileName")
      ..click();
`

**Comment by close2** [comment]
Hello @tkchung23 

Please add an UTF-8 BOM at the start of your file.  Otherwise excel will not use UTF8.

```dart
  List<List> wholeFile = [["姓", "名", "性別"], ["陳", "大文", "男"]];

  String csvString = ListToCsvConverter(fieldDelimiter: ';').convert(wholeFile);

  List<int> excelCsvBytes = [0xEF, 0xBB, 0xBF]
    ..addAll(utf8.encode(csvString));

  String base64ExcelCsvBytes = base64Encode(excelCsvBytes);


  print('<html><body>here we go: <a href="data:text/plain;charset=utf-8;base64,$base64ExcelCsvBytes" download="test1.csv">data</a></body></html>');

```

Steps:
* Use `;` as separator character
* Convert the csv String to UTF8
* Add the UTF8 BOM at the beginning: `0xEF`, `0xBB`, `0xBF`
* Convert to base64
* add `;base64` to the href

Good luck
