### ISSUE TITLE
CsvToListConverter return all the row data in single entry

### ISSUE THREAD

**Issue by dhaval-k-simformsolutions** [close2/csv#49]
I am using the CSV plugin to read data from existing CSV, When I try to pick a CSV file and perform `CsvToListConverter` it gives all CSV data as a single item in the list on behalf of separate rows in the list... 

I am using examples given in the package itself to read CSV.

You can test your example with this CSV: [https://figshare.com/articles/dataset/temperature_csv/3171766](https://figshare.com/articles/dataset/temperature_csv/3171766)

**Comment by bySabi** [comment]
@dhaval-k-simformsolutions I solved, my issue, using `(CsvToListConverter(eol: "\n")` maybe is valid for you too.

I was working with an example dataset downloaded from `kaggle.com` where row end of line is of LF unix type.

**Comment by mahanmarwat** [comment]
The package needs to detect the EOL.
I had the same issue but fixed it by passing the `eol` argument to the `CsvToListConverter().convert(data, eol: "\n")`
https://stackoverflow.com/a/71350383/3293340

**Comment by dhaval-k-simformsolutions** [comment]
> The package needs to detect the EOL. I had the same issue but fixed it by passing the `eol` argument to the `CsvToListConverter().convert(data, eol: "\n")` https://stackoverflow.com/a/71350383/3293340

Yes this is the correct way to fix it... we have to use "\n" while converting CSV to list and the same way list to CSV.
