### ISSUE TITLE
The numbers or time contain "\"

### ISSUE THREAD

**Issue by kevinxxq** [close2/csv#51]
Hi There,
Thank you for the package.
I tried to parse some csv file, but looks like there are something not working well.The numbers or timedate are deliminated with "\":

![image](https://user-images.githubusercontent.com/55800697/158003761-c4398d3f-8168-44c2-8ce7-268628e5e02c.png)

the code:
```
 // Read the file
    final strFile = await file.readAsString(
      encoding: systemEncoding,
    );
   
    List<List<dynamic>> listLines = const CsvToListConverter(
      eol: "\n",
      fieldDelimiter: ",",
      shouldParseNumbers: false,
    ).convert(strFile);
```

The data in csv file:
```
"Measurement position,,,50,150"
"Time stamp,2014-05-15,,14:21:25,14:21:25"
```

Thank you.

**Comment by close2** [comment]
I am not sure I understand the problem.

Is the problem that the `CsvToListConverter` splits the second line, even though it has a quote (`"`) at the beginning and end of the line?  That would indeed be a bug.

**Comment by close2** [comment]
I have taken another look at your screenshot.
I find it strange that `Time stamp` is offset by half a character.  Is it possible that you CSV file contains some strange unicode character instead of a simple `"`?

Closing for now.
