### ISSUE TITLE
Different output in debug and when deployed

### ISSUE THREAD

**Issue by andibardhi** [close2/csv#52]
![Screenshot_2](https://user-images.githubusercontent.com/51854918/159082712-4088265e-6771-402a-a948-ac3fcfca6a72.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/51854918/159082715-5a8d2c62-236d-4768-a24f-10c015922e20.jpg)
So I was testing CSV documents in flutter and when debugging I get a List of Lists (a list for each row) as you can see in the attachment, but when deploying I get a different result: A List of a List with every cell value (also attached). 
My code: 
`  Future<void> loadCSV() async {
    final _rawData = await rootBundle.loadString("assets/test.csv");
    List<List<dynamic>> listData = const CsvToListConverter().convert(_rawData);
    js.context.callMethod("alert", <String>["listData  $listData"]);
  }
`
Build command: 
`if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release`

**Comment by close2** [comment]
This is probably an end-of-line problem.

It is likely that your local system uses a different eol character than the system where the app is deployed.

You can either specify the EOL using the `eol` parameter, or use the `FirstOccurrenceSettingsDetector` (see README)

Please reopen if you eols are not the problem.
