### ISSUE TITLE
Multi Sheets per file ?

### ISSUE THREAD

**Issue by Joseph-Nathan** [close2/csv#54]
is it available to create multi-sheet in csv file ,
it can do in Numbers(MacOS)

**Comment by lil5** [comment]
You don't understand what a CSV file is 

> A comma-separated values (CSV) file is a delimited [text file](https://en.wikipedia.org/wiki/Text_file) that uses a [comma](https://en.wikipedia.org/wiki/Comma) to separate values. Each line of the file is a data [record](https://en.wikipedia.org/wiki/Record_(computer_science)). Each record consists of one or more [fields](https://en.wikipedia.org/wiki/Field_(computer_science)), separated by commas. The use of the comma as a field separator is the source of the name for this [file format](https://en.wikipedia.org/wiki/File_format). A CSV file typically stores [tabular](https://en.wikipedia.org/wiki/Table_(information)) data (numbers and text) in [plain text](https://en.wikipedia.org/wiki/Plain_text), in which case each line will have the same number of fields.
>
> \- https://en.wikipedia.org/wiki/Comma-separated_values

In Numbers (or any other Spreadsheet application) converting to CSV requires you to select a page from your multi-page spreadsheet.

@close2 please close
