### ISSUE TITLE
How to make each fields data to be enclosed with double quotes.

### ISSUE THREAD

**Issue by Sunsiha** [close2/csv#56]
Is there is anyway I can make it all fields data to be in double quoted? Now fields with comma(,) only coming as double quoted.

For example:

Current output:
1,Sunisha,sunisha@gmail.com,"Abbeville, Louisiana"

Expected output:

"1","Sunisha","sunisha@gmail.com","Abbeville, Louisiana"

pubspec:
``` csv: ^5.0.1```

**Comment by close2** [comment]
This is currently not supported.  There is already a feature request.  I just haven't found time to implement it.

https://github.com/close2/csv/issues/6
