### ISSUE TITLE
Issue compatibility with Flutter 3.10.x

### ISSUE THREAD

**Issue by arielramos** [close2/csv#64]
This dependency is awesome, and it was working fine until Flutter 3.10.x came out, now the definitions are not being recognized 

<img width="1001" alt="Screenshot 2023-06-23 at 9 56 26 PM" src="https://github.com/close2/csv/assets/11698932/ccccf881-3f4a-4400-9b19-78bdceaf1161">

**Comment by close2** [comment]
Hi @arielramos 

I don't think that this error has anything to do with this library.

Neither `selectFile` nor `utf8.decode` are part of the `csv` library.

Please reopen, if I am mistaken.

**Comment by arielramos** [comment]
Hi @close2 my mistake, you are right, the only think that I want to know is if this dependency has nullsafety?

**Comment by close2** [comment]
Hi @arielramos !
Yes the library has nullsafety.
